### PR TITLE
More Icon Overhauls for the Radial Menu. Added IsOnFriendsList Default Parameter.

### PR DESCRIPTION
**Pull request by BluWizard10**
Hi again! ^^

As I mentioned previously in DM with you, I wanted to redo some of the existing Icons being used so that it looks better on HiDPi displays. I've been working on touching them up one at a time. It ain't finished yet and there's still some left I wish to overhaul, hence why this is a Draft PR.

**Once I'm complete with my proposed icons, I'll mark this PR as Ready for Review.**

### Things to Know
Some of these Icons may not be exactly as they look 1:1 in-game, but created them to look as close as possible. For example, the icon `BSX_GM_Expressions.png` may look similar to what it looks like in-game, but it was re-traced from scratch to be as close as possible. The same can be said for the ones I'm working on right now for the Quick Actions section in the Expressions Menu. I also think the `BSX_GM_Generic.png` icon I made looked good as a replacement to `BSX_GM_Default.png` as well, so I hope all this is okay!

To also add to this, `BSX_GM_Emojis.png` and the other related ones containing the same icons were "re-borrowed" from the VRChat Discord, since they were already at a higher resolution. I assume you wanted to keep those in the Radial Menu to look as close as possible to the real Radial Menu in-game, so I hope this is okay as well!

### CODE REVIEW

**Comment by BluWizard10** [comment]
I will note that I have absolutely no clue when SDK 3.5.0 will ever release (since I've heard that's gonna be the one that supports Unity 2022.3). I myself have been eagerly waiting for the VRC Team to release it and hoping it's not too much longer.

I'm assuming you are aiming to release 3.8.8 at the same time when the SDK releases for Unity 2022.3. So if that's the case, then feel free to poke me if you think I should mark this PR Ready for Review sooner than later.

**Comment by BluWizard10** [comment]
This is it! All Icons have been upgraded and all should look excellent on HiDPi displays in the Unity Editor :D 

As a Bonus, VRChat v2023.4.2 (right now in Open Beta) added a brand new Default Parameter, called `IsOnFriendsList`. It's a Boolean that outputs `true` whenever someone who's on your Friends List is viewing your Avatar. `false` if otherwise. Documentation was updated with this detail. **Because of this, I already went ahead and updated the code, adding it in `Options -> Extras` sub-menu!** An Icon was made for that as well by yours truly.

Other than that, this PR is now Ready for Review!

**Comment by BlackStartx** [comment]
Hi Blu~ ^-^
Sorry for the late review~ 🌺 

First of all:
> I'm assuming you are aiming to release Gesture Manager v3.8.8 at the same time when the VRChat SDK releases for Unity 2022.3 support.

I would probably release a "**Gesture Manager 3.8.8**" version before the 2022 SDK since I do want to bump the compatibility before the actual SDK release~ (So users will not face the Creator Companion warning thinghie!)

As for 2022, the first official version after the update will surely be "**Gesture Manager 3.9.0**", and **MAY** be incompatible with 2019~

> [About the icons]

I do love them once again, also the one in the tool section! ;D

I'll probably merge them tomorrow since now it's kinda late~

**Comment by BluWizard10** [comment]
> I would probably release a "Gesture Manager 3.8.8" version before the 2022 SDK since I do want to bump the compatibility before the actual SDK release~ (So users will not face the Creator Companion warning thinghie!)

That makes sense. Probably a good idea to bump the compatibility anyways to get around that issue with Creator Companion.

> As for 2022, the first official version after the update will surely be "Gesture Manager 3.9.0", and MAY be incompatible with 2019~

That's good to know, considering it's gonna be a major compatibility update. Hope the VRC Team has some plans to make the transition in the Creator Companion easygoing to an extent.

> I do love them once again, also the one in the tool section! ;D

Yeah, had fun designing that one. ^^ 
Loosely based on how the Gizmos for Contact Receivers looks like in the Unity Editor.

> I'll probably merge them tomorrow since now it's kinda late~

Sounds good! Thanks :D

**Pull request merged**
